### ISSUE TITLE
"This component is not working"

### ISSUE THREAD

**Issue by AngelofromTurin** [akasma74/Hass-Custom-Alarm#24] opened 2019-07-02 19:45 UTC
**Your components (from Alarm/Settings/About):**
 - component version v1.8.0b

**Platform & Browser:**
 - hassio v0.95.4
 - crome

**Describe the bug**
i upgrade the component to improve hacs, restart the bwalarm with basinc config and reconfig again, it work but whene i add the name of my alarm component the web page say "This component is not working".
the alarm component is working but the page configuration is bloked... 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by akasma74** [comment] 2019-07-02 19:56
I'm afraid without clear instructions how to reproduce your issue I will only able to close it.

**Comment by AngelofromTurin** [comment] 2019-07-02 20:05
well... 
when i start the configuration of the bwalarm the alarm is down because dont have the name and the web page work but if i write the name for the alarm component its work but the bwalarm's page dont work and say : "This component is not working"
this is a partial of my bwalarm.yaml:

platform: bwalarm
name: home alarm
panel:
  cameras:
  - camera.ezviz_ingresso
  enable_clock: true
  panel_title: Home Alarm
  enable_weather: true
  shadow_effect: true
  enable_serif_font: false
  enable_camera_panel: true
  camera_update_interval: '5'
  enable_floorplan_panel: true
  floorplan: binary_sensor.floorplan
  enable_sensors_panel: true
enable_night_mode: false

**Comment by akasma74** [comment] 2019-07-02 21:15
Mate, can you ask someone with better English to help you?
I really don't understand what's your problem :(
I need to know how did you install/update the integration.
I'll need Home Assistant startup log as "This component is not working" is not enough.
And please enclose your config in three back quotes to preserve formatting.

**Comment by AngelofromTurin** [comment] 2019-07-03 08:24
Dear, I'm sorry for my bad english... try to be understable...
i want to personalize the name of my alarm,
platform: bwalarm
name: Home Alarm  <---------  thise the problem 
the alarm was : alarm_control_panel.home_alarm
but the web page of Bwalarm is thise...
![bwalarm](https://user-images.githubusercontent.com/46902587/60575837-8e467b00-9d7c-11e9-92e4-c24985d1ac06.png)

**Comment by akasma74** [comment] 2019-07-03 09:30
OK, that's better.
It's because you are using the wrong name.
This is internal name of the integration in HA.
You want to change title of web panel, that's setting in `panel:`
```
panel:
  cameras: []
  enable_clock: 'True'
  hide_sidebar: 'True'
  round_buttons: false
  enable_sensors_panel: 'True'
  enable_fahrenheit: 'False'
  panel_title: Home Alarm
  camera_update_interval: ''
  hide_sensors: 'True'
```

**Comment by AngelofromTurin** [comment] 2019-07-03 09:48
sorry but i don't want cahnge the panel title but the alarm name because my automation are for: 
alarm_control_panel.home_alarm not for alarm_control_panel.house and in the past version of bwalarm all work fine... now i must have thise default name "house" (alarm_control_panel.house) and rewrite all my automation?

**Comment by akasma74** [comment] 2019-07-03 10:02
Right.
Can you confirm that your past version had panel_custom.yaml?
Anyway, currently the only way I can see to solve your issue (if I understand it right) is you to open custom_component/bwalarm/alarm_control_panel.py and edit string [384](https://github.com/akasma74/Hass-Custom-Alarm/blob/master/custom_components/bwalarm/alarm_control_panel.py#L384) as:
```
        config={"alarmid": "alarm_control_panel.home_alarm"},
```
and restart Home Assistant.

Please let me know how if that helps.

**Comment by AngelofromTurin** [comment] 2019-07-03 10:20
don't remeber the past version of bwalarm... maybe i take your update just one month ago...
about thise problem now its ok 
i can have my personal name for the hassio's allarm component and see the bwalarm' web page
thanks

**Comment by akasma74** [comment] 2019-07-03 10:21
Hurray!

**Closed by akasma74** 2019-07-03 10:21 UTC
Labels: enhancement

**Comment by djtommye** [comment] 2019-07-25 07:56
Running hassio v96.4 - Each time I restart, in the log, I see "Overwriting integration alarm" followed by "components/frontend/__init__.py (WARNING). 

Any idea why I'm seeing this?

**Comment by djtommye** [comment] 2019-07-25 07:58
Another issue... when armed, the Alarm link on the sidebar takes to a page which displays the keypad to disarm.  However, if I use the lovelace card, I just see a disarm button with no keypad.

![alarm](https://user-images.githubusercontent.com/24887617/61856585-08ec4d00-ae88-11e9-8f6e-35bfffceb032.PNG)

**Comment by akasma74** [comment] 2019-07-25 08:29
mate, your issues have no bearing with this one. and this one is closed - why on Earth are you posting it here?
please open a new issue properly

**Comment by djtommye** [comment] 2019-07-25 12:53
My apologies - I was thinking I was on a forum.  I just submitted two reports.  Thank you.
