### ISSUE TITLE
Invalid Config

### ISSUE THREAD

**Issue by MagicMikey8** [akasma74/Hass-Custom-Alarm#74] opened 2020-01-25 19:41 UTC
**Your components (from Alarm/Settings/About):**
 - component version v1.11.2pre1

**Platform & Browser:**
 - Platform name & Home assistant version: Hass.io 0.104.3 [HassOS 3.8]
 - Browser name & version: Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Describe the bug**
After manual installation as per the readme instructions and multiple reboots of the RP, the following notification is given:

_The following integrations and platforms could not be set up:

mqtt
bwalarm.alarm_control_panel
Please check your config._

**To Reproduce**
1. Manually install 
2. Add line `alarm_control_panel: !include resources/bwalarm/bwalarm.yaml` to configuration.yaml
3. Reboot RP

**Expected behavior**
Some type of Alarm menu to appear in the side bar to start configuring the alarm panel.

[logs.txt](https://github.com/akasma74/Hass-Custom-Alarm/files/4112606/logs.txt)

**Comment by akasma74** [comment] 2020-01-25 19:49
I don't get what it is in step 2.

Could you confirm that you have [this](https://github.com/akasma74/Hass-Custom-Alarm/blob/master/custom_components/bwalarm/manifest.json) file into `<HA config folder/custom_components/bwalarm/`?

**Comment by MagicMikey8** [comment] 2020-01-25 20:02
I confirm that I have that file with exact same contents.

It is a fresh installation from today! I do have that file in the right directory and the contents are:

`platform: bwalarm`

**Comment by akasma74** [comment] 2020-01-25 20:21
thanks for confirming.
cannot reproduce it yet.. will dig deeper when I have time.

**Comment by MagicMikey8** [comment] 2020-01-26 01:33
After doing that, nothing related to this shows up in the logs and no longer have the notification above.

**Comment by akasma74** [comment] 2020-01-26 09:44
Are you saying that after removing this component from your HA config you have no errors in your HA log (namely, MQTT ones)?

**Comment by MagicMikey8** [comment] 2020-01-26 13:20
Yes, that is correct.

**Comment by akasma74** [comment] 2020-01-26 13:27
VERY strange. How on earth a custom component can affect setup of `mqtt` component:

> Setup failed for mqtt: Integration failed to initialize.

By the way, the log you posted here is pretty unusual as it includes only few things (no call stack for exception etc).

**Comment by MagicMikey8** [comment] 2020-01-26 14:06
See attached the full logs after reboot.

[full_logs.txt](https://github.com/akasma74/Hass-Custom-Alarm/files/4113541/full_logs.txt)

![full logs](https://user-images.githubusercontent.com/60295428/73136384-07f4cd80-401b-11ea-8cd9-f80ca39637be.jpg)

Thanks.

**Comment by akasma74** [comment] 2020-01-26 14:48
Oh, I see.
Do you have access (ssh/SAMBA) to the `home-assistant.log` file in four config folder. I need its content, not this one because it's shortened version, not the full log.

By the way, do you use mqtt in your HA setup at all? Is your MQTT broker configured and running properly?

**Comment by akasma74** [comment] 2020-01-27 12:46
I'm afraid I cannot reproduce the issue so unless you provide me with more evidence I will need to close it.

**Comment by akasma74** [comment] 2020-02-02 19:21
I'm closing this issue now because there was no response. Feel free to reopen it or create a new one if you need.

**Closed by akasma74** 2020-02-02 19:21 UTC
Labels: question
